
[functions.insert_to_queue]
enabled = true
verify_jwt = true
import_map = "./functions/insert_to_queue/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/insert_to_queue/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/insert_to_queue/*.html" ]

[functions.insert_parameters]
enabled = true
verify_jwt = true
import_map = "./functions/insert_parameters/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/insert_parameters/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/insert_parameters/*.html" ]

[functions.insert_to_parameters]
enabled = true
verify_jwt = true
import_map = "./functions/insert_to_parameters/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/insert_to_parameters/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/insert_to_parameters/*.html" ]
